### ISSUE TITLE
Min/max not respected on rij with default algorithm irijco = 1 (Code_Saturne 5.1.4)

### ISSUE THREAD

**Issue by RomainCamy** [code-saturne/code_saturne#1]
On a 14M cells grid with no quality problem according to the listing, in the "clipping" section Rii are < 0 on many cells (5%). Also the number of iterations required changes in one time step from ~200 to 10000 and back to ~200.
[listing.txt](https://github.com/code-saturne/code_saturne/files/1938692/listing.txt)

**Comment by YvanFournier** [comment]
Fixed (at least on master branch) by successive improvements between March and May 2018.
