### ISSUE TITLE
Bug when using LES with Lagrangian module

### ISSUE THREAD

**Issue by HJ632** [code-saturne/code_saturne#104]
Hi,

There appears to be an issue that prevents the use of LES with the Lagrangian module. Using Smagorinsky gives a 'mismatch in field' error for ustar, while using Dynamic Smagorinsky or WALE causes an immediate crash. This has occurred on every configuration that I have tried, with or without the turbulence based deposition model. I'm using version 7.0.4. I have attached a file containing three representative test cases. 
[LagrLESBug.zip](https://github.com/code-saturne/code_saturne/files/11220405/LagrLESBug.zip)

**Comment by YvanFournier** [comment]
Hello,

I'm not sure LES and the Lagrangian module are compatible yet, though I beleive someone is working on it. I'll update this issue when I know more about the timeline.

**Comment by YvanFournier** [comment]
Hello,

Sorry for the late update. I just fixed the "mismatch in field error" for the master, v8.0, and v7.0 branches.

I need to do the second adaptation now.
