### ISSUE TITLE
Error in file cs_auto_flags.sh for the Clang compiler

### ISSUE THREAD

**Issue by paspro** [code-saturne/code_saturne#105]
In file cs_auto_flags.sh, line 829 the code reads:

  `cxxlags_default="-Wall -Wshadow -Wpointer-arith -Wmissing-prototypes -Wuninitialized `-Wunused"``

and it should be:

`  cxxflags_default="-Wall -Wshadow -Wpointer-arith -Wmissing-prototypes -Wuninitialized -Wunused"`

**Comment by YvanFournier** [comment]
Fixed in commit af8a9815 (master) and 750fad41 (v8.0).
