### ISSUE TITLE
Cooling Tower output "cooling_towers_balance.01"

### ISSUE THREAD

**Issue by YohannEude** [code-saturne/code_saturne#11]
In order to use  autovnv/study manager easily (with some python scripts) is-it possible to change the third line of the output file "cooling_towers_balance.01"
from :

line 1   # Balance for the exchange zone 01
line 2   # ====================
line 3  	Time	Flux air/liq	Temp liq ....
To:

line 1  # Balance for the exchange zone 01
line 2   # ======================
line 3   #	Time	Flux air/liq	Temp liq ....

Thank you for your help

Yohann

**Comment by YvanFournier** [comment]
Done in commit 7968f3e (master, v5.3).
