### ISSUE TITLE
CS 8+ does not create checkpoint files

### ISSUE THREAD

**Issue by paspro** [code-saturne/code_saturne#112]
I have a problem with code_saturne 8-beta and master when running an unsteady flow case in the sense that the code does not create any checkpoint files in the checkpoint directory and therefore a restart is not possible. For the same case, code_saturne 7.3 works properly and it creates checkpoint files. 

The relevant setting in the setup.xml file is the following:

```
  <calculation_management>
    <block_io/>
    <partitioning/>
    <start_restart>
      <frozen_field status="off"/>
      <restart_rescue>0</restart_rescue>
    </start_restart>
  </calculation_management>

```

**Comment by paspro** [comment]
What I found out is that the specified maximum allowed time to run a case (unsteady run) influences the creation or not of checkpoints. For some values it does not create checkpoints and for others it does.

**Comment by paspro** [comment]
Any progress on this issue?

**Comment by YvanFournier** [comment]
Fixed.
