### ISSUE TITLE
Deprecated flag for darwin

### ISSUE THREAD

**Issue by paspro** [code-saturne/code_saturne#122]
In macOS 14.0 (Sonora) / Darwin 23.0.0 / Xcode 15.0 and the system's linker (ld) has changed.

In file cs_auto_flags.sh and line 136 the following link flags are specified:

`    ldflags_default_shared="-dynamiclib -undefined dynamic_lookup -undefined error"`

but the -undefined error option is deprecated and so this should be modified to:

`    ldflags_default_shared="-dynamiclib -undefined dynamic_lookup"`

the same applies to the ple_auto_flags.sh file and line 83 which should become:

`   ldflags_default_shared="-dynamiclib -undefined dynamic_lookup"`

**Comment by YvanFournier** [comment]
Updated on master and v8.0 branches and PLE master.

For master branch, PLE update will be done in a second PLE alignment stage (as this does not seem urgent if this is only a deprecation warning; do not hesitate to reopen issue otherwise).
