### ISSUE TITLE
run openfoam case in Saturn 

### ISSUE THREAD

**Issue by lkampoli** [code-saturne/code_saturne#131]
Hello, I have an openfoam test case of a body of revolution inside a pipe. I simulate it as an axisymmetric mesh built from block mesh OF utility. Which is the proper/best way to export it and run it in Saturn?

Thank you

**Comment by YvanFournier** [comment]
Hello,

For support questions, please use the code-saturne forum, and not the issue tracker.

Also, for the forum, do not forget to read the usage recommendations so as to help us answer.
