### ISSUE TITLE
error while installing codesaturn

### ISSUE THREAD

**Issue by alcarnielo** [code-saturne/code_saturne#133]
Good afternoon,

I was installing code saturn v8.1 following the instructions from this [tutorial]<https://www.youtube.com/watch?v=wVxtVCC9HKY&t=1603s> and I got this error:

<pre>Download of HDF5
  (https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.12.3/src/hdf5-1.12.3.tar.gz)
Traceback (most recent call last):
  File &quot;/home/alvaro/saturn-src/saturne_build/../code_saturne/install_saturne.py&quot;, line 1348, in &lt;module&gt;
    setup.install()
  File &quot;/home/alvaro/saturn-src/saturne_build/../code_saturne/install_saturne.py&quot;, line 1086, in install
    p.download()
  File &quot;/home/alvaro/saturn-src/saturne_build/../code_saturne/install_saturne.py&quot;, line 237, in download
    urllib.request.urlretrieve(self.url, self.archive)
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
</pre>

I changed the original code from this:
        self.packages['hdf5'] = \
            Package(name="HDF5",
                    description="Hierarchical Data Format",
                    package="hdf5",
                    version="1.12.3",
                    archive="hdf5-1.12.3.tar.gz",

                   url="https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.12.3/src/%s"

)

to this one (using a lower version of the hdf5 lib):
        self.packages['hdf5'] = \
            Package(name="HDF5",
                    description="Hierarchical Data Format",
                    package="hdf5",
                    version="1.12.0",
                    archive="hdf5-1.12.0.tar.gz",

                    url="https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.0/src/hdf5-1.12.0.tar.gz",

)

and it seems to partially solve the issue. 

But after that I am facing another one:

<pre>Download of MED
  (https://www.code-saturne.org/releases/external/med-5.0.0.tar.gz)
Traceback (most recent call last):
  File &quot;/home/alvaro/saturn-src/saturne_build/../code_saturne/install_saturne.py&quot;, line 1350, in &lt;module&gt;
    setup.install()
  File &quot;/home/alvaro/saturn-src/saturne_build/../code_saturne/install_saturne.py&quot;, line 1088, in install
    p.download()
  File &quot;/home/alvaro/saturn-src/saturne_build/../code_saturne/install_saturne.py&quot;, line 237, in download
    urllib.request.urlretrieve(self.url, self.archive)
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File &quot;/home/alvaro/miniconda3/lib/python3.11/urllib/request.py&quot;, line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found</pre>

for this one I tried to change this part of the code:
        self.packages['med'] = \
            Package(name="MED",
                    description="Model for Exchange of Data",
                    package="med",
                    version="5.0.0",

                    archive="med-5.0.0.tar.gz",

                    url="https://www.code-saturne.org/releases/external/%s")

to this one:
        self.packages['med'] = \
            Package(name="MED",
                    description="Model for Exchange of Data",
                    package="med",
                    version="5.0.0",

                    archive="med-5.0.0.tar.bz2",

                    url="https://www.code-saturne.org/releases/external/%s")

in the end, none of these modifications worked completely. I faced several other errors after the processing that I couldn't solve.

A simple solution would be to include the missing files into the paths.

**Comment by YvanFournier** [comment]
Hello,

Could you test with the modified install file here ? If it is OK, I'll push it to v8.1 and master branches.
I needed to do another change when extracting HDF5 as it added a "./" component to the path, which broke the script.

[install_saturne.py.gz](https://github.com/code-saturne/code_saturne/files/13801521/install_saturne.py.gz)

**Comment by alcarnielo** [comment]
Hello, 

I just managed to run the code and it worked perfectly for me. Thanks for the return and update
