### ISSUE TITLE
Impossible to add the "velocity" field for the Time average through the GUI

### ISSUE THREAD

**Issue by YohannEude** [code-saturne/code_saturne#135]
Hello the team,

In the MASTER version (from today), it is no more possible to add the "velocity" field (the vector one, not the components) for the Time average through the GUI.

Cheers,

Yohann

**Comment by YvanFournier** [comment]
Hello.

Fixed in 0e6e282c6.

**Comment by YohannEude** [comment]
it solved in the setup.xml but in the GUI, the "Velocity vector field" is not visible under "Variables" into the line of the time average object when you add one.

Cheers,

Yohann
