### ISSUE TITLE
Problems with Qt5

### ISSUE THREAD

**Issue by Pepe-87** [code-saturne/code_saturne#136]
Good morning! 
I tried in vain today to use code saturne; it worked great, but days ago i installed (and then removed) spyder5 by pip.
since then, I started to have issues with PyQt5 :(
After typing the command `code_saturne gui` in the terminal, this appeared:

`user@my_laptop:~$ code_saturne gui` 
`Cannot mix incompatible Qt library (5.15.2) with this library (5.15.3)` 
`Aborted (core dumped)`

I am using Code Saturne 8.03 on Xubuntu 22.04 LTS
How can i fix it?

**Comment by YvanFournier** [comment]
Hello,

The error messageexplains it all.

If you follow the recommendations on the Wiki here (https://github.com/code-saturne/code_saturne/wiki/Pre-installation:-Linux-distribution-packages), you do not need to use pip to install PyQt.

Only use pip if you understand its behaviour well enough : unless you force the version number, a reinstall may install a more recent version.
If that happens, you simply need to reinstall code_saturne so as to relink-it with the correct version.

**Comment by Pepe-87** [comment]
> Hello,
> 
> The error message explains it all.
> 
> If you follow the recommendations on the Wiki here (https://github.com/code-saturne/code_saturne/wiki/Pre-installation:-Linux-distribution-packages), you do not need to use pip to install PyQt.
> 
> Only use pip if you understand its behaviour well enough : unless you force the version number, a reinstall may install a more recent version. If that happens, you simply need to reinstall code_saturne so as to relink-it with the correct version.

Thanks Yvan, yeah, i read everything and compiled again.
Everything works great now.
Thank you very much )))
