### ISSUE TITLE
trasnposed gradient and secondary viscosity terms to be multiplied by idiff ?

### ISSUE THREAD

**Issue by rbresson** [code-saturne/code_saturne#15]
Hello,

I noticed that even if I disable diffusion for the velocity, the  trasnposed gradient and secondary viscosity terms are still taken into account.

Indeed, they are not multiplied by idiff in cs_convection_diffusion.c

Is that the expected behaviour ? It does not seem right to me.

Thanks

Raphael

**Comment by rbresson** [comment]
I just saw that it has been corrected in version 5.2.
I was working with version 5.0.
So I guess you can close the topic.

**Comment by YvanFournier** [comment]
Hello,

As modifying the behavior of 5.0 (stable) would be risky, I'll simply close the issue.
