### ISSUE TITLE
Calculation of wall_dist does not converge on first time steps (even after a restart) (Code_Saturne 5.1.4)

### ISSUE THREAD

**Issue by RomainCamy** [code-saturne/code_saturne#2]
On a 225M cells grid with no quality problem according to the listing, the ~25 first time steps show the warning message that the calculation of wall_dist does not converge. After the message disappears and will only reappear at the beginning of the next restart.
[listing.txt](https://github.com/code-saturne/code_saturne/files/1938776/listing.txt)

**Comment by RomainCamy** [comment]
OK. The commits 15713e4 and more recents {cc82934, 36bf24f, 65761f1} limit the calculation time but still the max number of iteration is reached and overall the calculation time is bigger on my test case by a factor ~1.5 (for each complete time step) compared to a simple modification of epsilo = 1.e-5. This is unexpected, isn't it ?
[listing-with-lasts-commits.txt](https://github.com/code-saturne/code_saturne/files/1943790/listing-with-lasts-commits.txt)
[listing-with-epsilo-1e-5.txt](https://github.com/code-saturne/code_saturne/files/1943791/listing-with-epsilo-1e-5.txt)

**Comment by MartinFerrand** [comment]
Commit adbfdba changes the way the dimensionless wall distance is computed in LES (iturb=40).
    The steady equation is solved once (no need of over iterations). In case of restart, do not start with a big value. By default now, the linear solver precision is 1.d-5 now.

**Comment by MartinFerrand** [comment]
Commit 2f2bad8 fix the last issue concerning cells with exactly zero on the diagonal (cells "in the center" of the domain). The gain in term of CPU has been drastically improved.
