### ISSUE TITLE
 Vof - Mixture global mass budget

### ISSUE THREAD

**Issue by LucianoGarelli** [code-saturne/code_saturne#28]
I was using the Vof algorithm in CS 5.0.9 and CS 5.3 to solve a 2D dam-break getting different results. The results were compared with the experimental and numerical results of the following paper: doi.org/10.1016/j.ijmultiphaseflow.2018.08.003 (Figs 4 and 7 of the paper)

When running with CS 5.0.9 the front of the wave hit earlier the obstacle, due to a bigger velocity. When reducing the Co number (0.5 -> 0.05) the result change significantly  (see Fig_1 attached) and converge to the results of CS 5.3. The case was running with a SIMPLEC P-V coupling, because the PISO coupling diverge for this problem in CS 5.0.9. With CS 5.3 the problem run correctly for SIMPLEC and PISO coupling and the results are very close to that reported in the reference (see Fig_2 attached). About that issue I can't find the problem. I attach the dam break case.

The problem in CS 5.3 is the report of the "Mixture global mass budget", which is wrong. Debugging the code I found that the value of the array "croma" containing the density at cell centers at previous time step is not being updated and have the initial ones when using it in the vof_print_mass_budget() subroutine. Following the history of change in 5.0.9 the  density at time step n-1 was updated in the section 5.bis of tridim.f90. This section was  removed in 5.3 in the commits 9fb8530  and a2ddc3b, and I think that was move to varpos.f90 and then to addfld.f90. I attach a text file were is printed for a cell the density for the steps n and n-1 and the mass budget. I modify the tridim in order to update the croma array (diff file attached).

In the equation presented in the documentation the void fraction at n and n-1 are used to compute mass budget, but in the subroutine the densities at n and n-1 are used.

![fig_1](https://user-images.githubusercontent.com/45599605/49805810-e2343880-fd34-11e8-895a-8d82447d5650.png)
[Fig_2.pdf](https://github.com/code-saturne/code_saturne/files/2667869/Fig_2.pdf)
[mass_budget.txt](https://github.com/code-saturne/code_saturne/files/2668016/mass_budget.txt)
[diff_tridim.txt](https://github.com/code-saturne/code_saturne/files/2668037/diff_tridim.txt)
[CS_files.zip](https://github.com/code-saturne/code_saturne/files/2668042/CS_files.zip)

**Comment by MartinFerrand** [comment]
Hi Luciano,
Thank you for the report. As far as I understand it seems that it is the print of the budget is wrong. 

We will look at that and will come back to you.
Best Regards

**Comment by MartinFerrand** [comment]
Hello again, 

[patch.tar.gz](https://github.com/code-saturne/code_saturne/files/2999111/patch.tar.gz)
could you test the attached patch (trunk version) ?

**Comment by LucianoGarelli** [comment]
Hi Martin,

I test the patch with the trunk version without success. After few time step the solution diverge. I attach the listing, setup.log and the xml for the cases using V5.3 and V6.1-beta. A variable density has to be used in the new version (after applying the patch).

Best Regards
[CS_Resu_files.zip](https://github.com/code-saturne/code_saturne/files/3018208/CS_Resu_files.zip)

**Comment by YvanFournier** [comment]
Hello Luciano,

Checking with another colleague who recently worked on the VOF model,  it seems the issue should have been fixed in the current version (v7.0 beta, undergoing validation). So I guess we can close it.

If you need up to date VOF setup examples, we can handle that on the forum. If you still have issues with the current version, do not hesitate to reopen this issue.

Best regards
