### ISSUE TITLE
"code_saturne submit" command w/ id-prefix adds quotation marks (v5.0.4)

### ISSUE THREAD

**Issue by PhilippNguyen** [code-saturne/code_saturne#3]
Version 5.0.4 adds quotation marks around the id-prefix, if the command "code_saturne submit" is used, for example 're2017_120x041x064_LES_pr071_'20180502-1654, what prevents the simulation from being started.

**Comment by PhilippNguyen** [comment]
please disregard, leaving the quotation marks away solves the problem.

**Comment by YvanFournier** [comment]
In your example, the quotation marks ended in the middle of the string, which probably caused the issue. If you need such placement of quotation marks, using escape characters (\') might work, though we would need to check.

In any case, as per your recommendation I am closing this issue.
