### ISSUE TITLE
Lagrangian: deposition without elimination and lack of deposition model

### ISSUE THREAD

**Issue by mathrack** [code-saturne/code_saturne#30]
https://github.com/code-saturne/code_saturne/blob/4748815a83f52cf6eb8d463ee772e0b956229635/src/lagr/cs_lagr_tracking.c#L1229

This line seems problematic when cs_glob_lagr_model->deposition = 0, which is the default setup. A workaround could be to call it only when

``if (cs_glob_lagr_model->deposition == 1)``

This is exactly what is done line 1197 for the deposition with elimination https://github.com/code-saturne/code_saturne/blob/4748815a83f52cf6eb8d463ee772e0b956229635/src/lagr/cs_lagr_tracking.c#L1197

**Comment by YvanFournier** [comment]
Fixed in v6.0, v5.3.2, v5.2.2, and v5.0.10.
