### ISSUE TITLE
Allow creation of mesh_input from GUI

### ISSUE THREAD

**Issue by mathrack** [code-saturne/code_saturne#36]
The possibility to do a restart from a simulation performed on another mesh is very interesting. As it requires a mesh_input or a mesh_output, it would be convenient to have a checkbox in the GUI to force the creation of such a file. Currently, the files can be obtained with the tool cs_preprocess or with the routine cs_user_mesh_save.

**Comment by YvanFournier** [comment]
Handled by commit 497e27bf.
