### ISSUE TITLE
Typo in bin/model/MainFieldsInitializationModel.py

### ISSUE THREAD

**Issue by mathrack** [code-saturne/code_saturne#37]
The compilation of the trunk version seems broken since this commit

https://github.com/code-saturne/code_saturne/blob/ba7f6a150e83d9941788961a702143d082e8a104/bin/model/MainFieldsInitializationModel.py#L104

**Comment by YvanFournier** [comment]
Fixed in master and v6.0 branch by referenced commits.

Thanks for the bug report.
