### ISSUE TITLE
Trackcvg fonts issue

### ISSUE THREAD

**Issue by LucianoGarelli** [code-saturne/code_saturne#49]
I get an error if in the track converge windows the fonts type or size are changed.  After in the execution of "code_saturne trackcvg" the following error appears:

\\\\\\\\\\\\\\\\\\\\
MainView.py", line 626, in ui_initialize
    if (font.fromString(from_qvariant(f, to_text_string))):
NameError: global name 'to_text_string' is not defined
\\\\\\\\\\\\\\\\\\\

The solution that I found was add to the MainView.py the following modification:
from code_saturne.Base.QtPage import getexistingdirectory **,to_text_string**

If the fonts are restored to the default value the problem is also solved.
I test in the CS 6 beta.

**Comment by YvanFournier** [comment]
Fixed.
