### ISSUE TITLE
ALE boundary condition for Free inlet/outlet type

### ISSUE THREAD

**Issue by LucianoGarelli** [code-saturne/code_saturne#51]
When using a deformable mesh and one of the boundaries conditions is free inlet/outlet there is no drop-down list to define the ALE BC. This issue arise in this post
[https://www.code-saturne.org/forum/viewtopic.php?f=2&t=2521#p13729](https://www.code-saturne.org/forum/viewtopic.php?f=2&t=2521#p13729)

I test it CS version 5.10 and 6.1-alpha.

![image](https://user-images.githubusercontent.com/45599605/64761518-a07a2d80-d512-11e9-9e3b-f2265559da95.png)

**Comment by YvanFournier** [comment]
Fixed by commit ab6fe2cc (starting with v6.2), merged in v6.0 branch (next v6.0.6) with commit b75d494a7.
