### ISSUE TITLE
[6.0] Overlay of boundary zones defined in the GUI

### ISSUE THREAD

**Issue by mathrack** [code-saturne/code_saturne#61]
Hello,

Trying to set up a case with version 6.0. I have defined boundary zones in the GUI and in cs_user_zones. However, when trying to set overlay for a boundary zone defined in the GUI from cs_user_zones, cs_boundary_zone_by_name returns a random number for the zone id. Using directly the zone id available in the GUI works like a charm. Is this the expected behavior ? See code below.

Thanks,
Cédric

```void
cs_user_zones(void)
{
    int z_id = 1;//cs_boundary_zone_by_name("Sol");
    cs_boundary_zone_set_overlay(z_id, true);
    [...]
}
```

**Comment by YvanFournier** [comment]
Hello,

`cs_boundary_zone_by_name` should directly return a pointer to the zone, not its id, so you can try:
```
cs_zone_t *z = cs_boundary_zone_by_name("Sol");
cs_boundary_zone_set_overlay(z->id, true);
```

**Comment by mathrack** [comment]
Then, this is the expected behavior, thank you for the reminder.
