### ISSUE TITLE
imodak update with the GUI

### ISSUE THREAD

**Issue by YohannEude** [code-saturne/code_saturne#68]
Hello,
It seems that the imodak option is not updated with the GUI (Thermal model->absorption coefficient-> Modak) . I did some tests with different options and it seems that "imodak" is always = 0 (do not use Modak) when I check in the setup.log.

Thank you for your help,

Regards,

Yohann

**Comment by YvanFournier** [comment]
Thanks for the report. Fixed in master, 6.2, 6.1, and 6.0 branches.
