### ISSUE TITLE
Issues when creating wall layers with user coding

### ISSUE THREAD

**Issue by nicolastonello** [code-saturne/code_saturne#7]
Depending on the geometry and the settings, the wall layer algorithm can create interpenetrating cells, resulting in meshes unsuitable for calculations.

**Comment by YvanFournier** [comment]
### Issue as analyzed on a small mesh

For example, given the following mesh (viewed as a cut in "crinkly" mode:

![bl_limit_ref](https://user-images.githubusercontent.com/5770167/45295901-8c1ae380-b500-11e8-9daf-813284fc9a44.png)

Inserting 2 layers with a relative thickness (and expansion factor 0.8) leads to the following issue:

![bl_limit_r_pb](https://user-images.githubusercontent.com/5770167/45295992-da2fe700-b500-11e8-9152-535742e37e62.png)

Viewed in from another angle with transparency and negative-volume cells in red:

![bl_limit_r_pb_t](https://user-images.githubusercontent.com/5770167/45296023-f6cc1f00-b500-11e8-9184-13730855de72.png)

Using a fixed thickness of 0.05, results are even worse on this case:

![bl_limit_f_pb](https://user-images.githubusercontent.com/5770167/45296051-119e9380-b501-11e8-95b5-ed8841933221.png)
![bl_limit_f_pb_t](https://user-images.githubusercontent.com/5770167/45296065-1b27fb80-b501-11e8-96dd-3c0e1ef9a736.png)

Proposed solution

A solution (commit 726394e76) is to test for negative volumes while deforming the mesh, and locally limit the extrusion on adjacent boundaries (removing one extrusion layer at vertices of those cells). This is done iteratively until no negative volume cells are produced.

This method also allows flattening cells beyond a given threshold relative to their initial volume.

Using a volume ratio limit of 0.15, we obtain the following mesh using the relative boundary layer thickness: 
![bl_limit_r_ok](https://user-images.githubusercontent.com/5770167/45296661-08aec180-b503-11e8-88a3-71b4ea034396.png)

With the fixed thickness:

![bl_limit_f_ok](https://user-images.githubusercontent.com/5770167/45296673-15331a00-b503-11e8-9310-ab8683db56e6.png)

Using a negative minimum volume factor, no limiter is used, and we revert to the previous behavior.
