### ISSUE TITLE
Misprint in the doc and comment in src

### ISSUE THREAD

**Issue by YohannEude** [code-saturne/code_saturne#70]
Hi,

I found two little errors in doc and src:
- for idilat = 0 0: Boussinesq approximation (rho constant **expect** in the buoyant term where...)
 -> "expect" would be replaced by "except"
- xsoot (isoot) in cs_user_parameters.f90:
!        if =  0   constant fraction of **fuel** Xsoot
whereas xsoot is a constant fraction of "product"

Regards,

Yohann

**Comment by YvanFournier** [comment]
Fixed in commit 61cede11.
