### ISSUE TITLE
Little bug in the GUI (Clipping)

### ISSUE THREAD

**Issue by YohannEude** [code-saturne/code_saturne#71]
Hi,

When you add a scalar and go in Numerical parameters/Equation parameters (clipping) and put the mousse on the scalar an error appear in the terminal about "toolTipRole". To solve that we just replace in NumericalParamRquationView.py line 824 "return self.toolTipRole[col]" by "return None" as it is done in the rest of the code.

Regards

Yohann

**Comment by YvanFournier** [comment]
Fixed in commit 82953619.
Thanks for the bug report.
