### ISSUE TITLE
Volume source term for coupling with syrthes 

### ISSUE THREAD

**Issue by KennethChinembiri** [code-saturne/code_saturne#85]
Good Afternoon, 

I have a minor bug to report. In cs_syr_coupling_volume_source_terms there is no call to cs_syr4_coupling_ts_contrib. This means the arrays ctbimp and ctbexp used to compute the volumetric sources stay at the initialized values. Effectively, the volumetric sources arrays for  st_exp and st_imp remain as zero. 

The bug is in the latest release Code_Saturne 7.0.0 and file cs_syr_coupling.c. 

Kind regards, 

Kenneth

**Comment by YvanFournier** [comment]
Hello,

Thanks for the report. This was also reported outside this bug-tracker by another user and fixed in commit e26781dd shortly after the v7.0.0 release. The fix is also applied to the v7.0 branch, so it will be in the v7.0.1 maintenance release, which should be released late July or August.
