### ISSUE TITLE
SMGR: there is no folder DATA SRC and MESH created by studymanager + FIX

### ISSUE THREAD

**Issue by kikuznetsov** [code-saturne/code_saturne#90]
Hello, 

There is a problem with studymanager in master branch: it does not create DATA, SRC and MESH folders. Here is a patch to fix this problem
[0001-SMGR-fix-to-overwrite-DATA-SRC-and-MESH-folders.patch.zip](https://github.com/code-saturne/code_saturne/files/8171002/0001-SMGR-fix-to-overwrite-DATA-SRC-and-MESH-folders.patch.zip)

**Comment by kikuznetsov** [comment]
But I have a doubts maybe you do not create folders DATA, SRC and MESH on purpose?

**Comment by YvanFournier** [comment]
Yes, this is voluntary. See the commit message for 56763da6dc757142f04f9abc7a739db0ec9e95c0.

This allows requiring only a source repository (usually under version control, such as Git), and a destination/output directory, without an intermediate directory as before.

**Comment by YvanFournier** [comment]
https://github.com/code-saturne/code_saturne/blob/master/docs/doxygen/user_guide/studymanager.md#how-to-convert-deprecated-prepro-scripts
