### ISSUE TITLE
Installation error (Error during configure stage of CGNS)

### ISSUE THREAD

**Issue by ibanagirre** [code-saturne/code_saturne#92]
During the installation of the prerequisite programs CGNS failed to install, the last install log message is "/bin/sh: 1: cmake: not found". I attach the install log for a better understanding of the possible error.

Thanks beforehand.

[install_saturne.log](https://github.com/code-saturne/code_saturne/files/8549524/install_saturne.log)

**Comment by paspro** [comment]
You need to install cmake in order to be able to build CGNS.

**Comment by ibanagirre** [comment]
Thanks!
I'm new to linux and I have a lot to learn.

kind regards.
